// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okgegpnaiwdyppxhhyec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rZ2VncG5haXdkeXBweGhoeWVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MjQ4MjgsImV4cCI6MjA3MzQwMDgyOH0.MyUcH2K5GhSlW16k992ZUy7pvvxKfEYS_MAgDtMFD3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});